# RK3566 Home Assistant Green Board
BOARD_NAME="HA Green"
BOARDFAMILY="rk35xx"
BOOTCONFIG="ha-green-rk3566_defconfig"
BOOT_SOC="rk3566"
KERNEL_TARGET="current"
FULL_DESKTOP="yes"
BOOT_LOGO="desktop"
BOOT_FDT_FILE="rockchip/rk3566-ha-green.dtb"
#IMAGE_PARTITION_TABLE="gpt"
